export const images = {
    backArrow: require('../assets/back.png'),
    user: require('../assets/user.png'),
    edit: require('../assets/edit.png'),
    logo: require('../assets/logo.png'),
    accountGroup: require('../assets/accountGroup.png'),
    plus: require('../assets/plus.png'),
    clock: require('../assets/clock.png'),
    summaryLogo: require('../assets/summaryLogo.png'),
    settingsLogo: require('../assets/settingsLogo.png'),
    CreateGroup: require('../assets/CreateGroup.png'),
    share: require('../assets/share.png'),
    expanseGroup: require('../assets/expanseGroup.png'),
    copy: require('../assets/copy.png'),
}